In [1]:
import pandas as pd
import numpy as np 
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import sklearn 

In [2]:
df= pd.read_csv("df_localidad.csv")

In [3]:
df

Unnamed: 0  precipitacion  Campaña  mes      Cultivo  idProvincia  \
0              29           56.2  1987/88  1.0      Alpiste            6   
1              30           56.2  1987/88  1.0      Alpiste            6   
2              39           56.2  1987/88  1.0      Alpiste            6   
3              70           56.2  1987/88  1.0        Avena            6   
4             100           56.2  1987/88  1.0        Avena            6   
...           ...            ...      ...  ...          ...          ...   
16262      263796            NaN  2019/20  NaN  Trigo total            6   
16263      263800            NaN  2019/20  NaN  Trigo total            6   
16264      263801            NaN  2019/20  NaN  Trigo total            6   
16265      263825            NaN  2019/20  NaN  Trigo total            6   
16266      263830            NaN  2019/20  NaN  Trigo total            6   

       idDepartamento  Sup_Sembrada  Sup_Cosechada  Producción  Rendimiento  
0                 462            50           50.0        50.0       1000.0  
1                 469           170          160.0       190.0       1188.0  
2                 686           400          400.0       480.0       1200.0  
3                 210          2200            0.0         0.0          0.0  
4                 413          3500          300.0       600.0       2000.0  
...               ...           ...            ...         ...          ...  
16262             413         32000        32000.0    134400.0       4200.0  
16263             462         28000        27200.0    103360.0       3800.0  
16264             469         51000        49325.0    180036.0       3650.0  
16265             686         30000        29750.0    130900.0       4400.0  
16266             714         35300        33718.0    144987.0       4300.0  

[16267 rows x 11 columns]

In [4]:
#borramos los datos NaN
df.dropna(inplace=True)

In [5]:
del df['Unnamed: 0']

In [6]:
def Rendimiento(Rendimiento:str) -> int:
    """
    This function encodes the rendimiento variable.
    """
    
    if Rendimiento >= 2000: return 1
    else: return 0

In [7]:
df["Rendimiento"] = df["Rendimiento"].apply(Rendimiento)

In [8]:
df


precipitacion  Campaña   mes      Cultivo  idProvincia  idDepartamento  \
0               56.2  1987/88   1.0      Alpiste            6             462   
1               56.2  1987/88   1.0      Alpiste            6             469   
2               56.2  1987/88   1.0      Alpiste            6             686   
3               56.2  1987/88   1.0        Avena            6             210   
4               56.2  1987/88   1.0        Avena            6             413   
...              ...      ...   ...          ...          ...             ...   
15821          157.0  2014/15  12.0  Trigo total            6             413   
15822          157.0  2014/15  12.0  Trigo total            6             462   
15823          157.0  2014/15  12.0  Trigo total            6             469   
15824          157.0  2014/15  12.0  Trigo total            6             686   
15825          157.0  2014/15  12.0  Trigo total            6             714   

       Sup_Sembrada  Sup_Cosechada  Producción  Rendimiento  
0                50           50.0        50.0            0  
1               170          160.0       190.0            0  
2               400          400.0       480.0            0  
3              2200            0.0         0.0            0  
4              3500          300.0       600.0            1  
...             ...            ...         ...          ...  
15821         16000        16000.0     62400.0            1  
15822         14710        14710.0     58840.0            1  
15823         26080        26080.0    101710.0            1  
15824         15000        15000.0     63000.0            1  
15825          9800         9700.0     36860.0            1  

[15826 rows x 10 columns]

In [9]:
#cambiamos rendimiento por Target que es lo que buscamos predecir
df["target"] = df["Rendimiento"]

In [10]:
df

precipitacion  Campaña   mes      Cultivo  idProvincia  idDepartamento  \
0               56.2  1987/88   1.0      Alpiste            6             462   
1               56.2  1987/88   1.0      Alpiste            6             469   
2               56.2  1987/88   1.0      Alpiste            6             686   
3               56.2  1987/88   1.0        Avena            6             210   
4               56.2  1987/88   1.0        Avena            6             413   
...              ...      ...   ...          ...          ...             ...   
15821          157.0  2014/15  12.0  Trigo total            6             413   
15822          157.0  2014/15  12.0  Trigo total            6             462   
15823          157.0  2014/15  12.0  Trigo total            6             469   
15824          157.0  2014/15  12.0  Trigo total            6             686   
15825          157.0  2014/15  12.0  Trigo total            6             714   

       Sup_Sembrada  Sup_Cosechada  Producción  Rendimiento  target  
0                50           50.0        50.0            0       0  
1               170          160.0       190.0            0       0  
2               400          400.0       480.0            0       0  
3              2200            0.0         0.0            0       0  
4              3500          300.0       600.0            1       1  
...             ...            ...         ...          ...     ...  
15821         16000        16000.0     62400.0            1       1  
15822         14710        14710.0     58840.0            1       1  
15823         26080        26080.0    101710.0            1       1  
15824         15000        15000.0     63000.0            1       1  
15825          9800         9700.0     36860.0            1       1  

[15826 rows x 11 columns]

In [11]:
#borramos  la columna de Rendimiento que no la reemplazo "target"
del df["Rendimiento"]


In [12]:
#borramos las columnas categoricas de "campaña" y "cultivo"
del df["Campaña"]


In [13]:
del df["Cultivo"]

In [14]:
#Deep=true en el metodo Copy, signidica que quiero aplicar la data del DF originaly hacer cambios
#sin que esto afecte la data original
X = df.drop(columns=["target"]).copy(deep=True)

In [15]:
X.head()

precipitacion  mes  idProvincia  idDepartamento  Sup_Sembrada  \
0           56.2  1.0            6             462            50   
1           56.2  1.0            6             469           170   
2           56.2  1.0            6             686           400   
3           56.2  1.0            6             210          2200   
4           56.2  1.0            6             413          3500   

   Sup_Cosechada  Producción  
0           50.0        50.0  
1          160.0       190.0  
2          400.0       480.0  
3            0.0         0.0  
4          300.0       600.0

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15826 entries, 0 to 15825
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   precipitacion   15826 non-null  float64
 1   mes             15826 non-null  float64
 2   idProvincia     15826 non-null  int64  
 3   idDepartamento  15826 non-null  int64  
 4   Sup_Sembrada    15826 non-null  int64  
 5   Sup_Cosechada   15826 non-null  float64
 6   Producción      15826 non-null  float64
dtypes: float64(4), int64(3)
memory usage: 989.1 KB


In [17]:
y= df["target"].copy(deep=True)

In [18]:
y.sample(15)

11201    1
10074    1
2132     0
2560     1
5800     1
6991     1
867      1
11472    0
7570     0
3492     1
7781     1
14814    1
1754     0
2765     0
6835     1
Name: target, dtype: int64

In [19]:
#Preparando la data para el training
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.33, random_state=42)

In [21]:
#importamos algoritmos
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.linear_model import LogisticRegression #Regresion logistica
from sklearn.ensemble import RandomForestClassifier # Random Forest

In [22]:
knn=KNeighborsClassifier() #neighbors = 5 (default)
lgr= LogisticRegression()
rfc= RandomForestClassifier() # trees=100 (Default)

In [23]:
print(type(knn))
print(type(lgr))
print(type(rfc))

<class 'sklearn.neighbors._classification.KNeighborsClassifier'>
<class 'sklearn.linear_model._logistic.LogisticRegression'>
<class 'sklearn.ensemble._forest.RandomForestClassifier'>


In [24]:
#train Knn
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [25]:
#Predict whit KNN
knn.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [26]:
y_test

8273     1
169      1
14862    1
8845     1
4098     0
        ..
7556     1
549      1
12299    1
13202    1
13449    1
Name: target, Length: 5223, dtype: int64

In [27]:
#train logistic Regretion
lgr.fit(X_train, y_train)

C:\Users\Gianluca\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
#predict whit logistic Reg
lgr.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [29]:
#train random forest
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [30]:
#Predict whit random forest
rfc.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)